name: PHP Composer

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    strategy:
      matrix:
        dependencies:
          - locked
          - highest
        php:
          - 8.1
          - 8.2
        include:
          - php-version: 8.2
            composer-options: "--ignore-platform-reqs"

    continue-on-error: ${{ matrix.php == '8.2' }}

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php }}"
          ini-values: memory_limit=-1

      - name: "Install composer and dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer-options }}

      - name: Run Lint Checker suite
        run: composer php-lint

      - name: PHPStan test
        run: composer phpstan

      - name: Run test suite
        run: composer test